# Generated by Django 3.2.6 on 2021-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.URLField()),
                ('head_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home Data',
            },
        ),
    ]
