# Generated by Django 3.2.6 on 2021-08-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='home_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
