# Generated by Django 3.2.6 on 2021-08-16 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_homemodel_home_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='home_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Enter Description here'),
        ),
    ]
