# Generated by Django 3.2.6 on 2021-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_homemodel_home_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_head_image', models.ImageField(upload_to='about_images/')),
                ('about_head_text', models.CharField(max_length=100)),
                ('about_head_sub_text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page Data',
            },
        ),
    ]
