# Generated by Django 3.2.6 on 2021-08-19 09:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='about_page_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Enter Description on what the Page is about'),
        ),
    ]
